# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
 orderer0.example.com:
    container_name: orderer0.example.com
    extends:
      file: base.yaml
      service: orderer
    volumes:
    - ./channel/genesis.block:/var/hyperledger/orderer/genesis.block
    - ./crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/msp:/var/hyperledger/orderer/msp
    - ./crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050
#    depends_on:
#      - kafka0
#      - kafka1
#      - kafka2
#      - kafka3
#
#  orderer1.example.com:
#    container_name: orderer1.example.com
#    extends:
#      file: base.yaml
#      service: orderer
#    volumes:
#    - ./channel/genesis.block:/var/hyperledger/orderer/genesis.block
#    - ./crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/msp:/var/hyperledger/orderer/msp
#    - ./crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/tls/:/var/hyperledger/orderer/tls
#    ports:
#      - 8050:7050
#    depends_on:
#      - kafka0
#      - kafka1
#      - kafka2
#      - kafka3
#
#  orderer2.example.com:
#    container_name: orderer2.example.com
#    extends:
#      file: base.yaml
#      service: orderer
#    volumes:
#    - ./channel/genesis.block:/var/hyperledger/orderer/genesis.block
#    - ./crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/msp:/var/hyperledger/orderer/msp
#    - ./crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/:/var/hyperledger/orderer/tls
#    ports:
#      - 9050:7050
#    depends_on:
#      - kafka0
#      - kafka1
#      - kafka2
#      - kafka3
      
    extra_hosts:
      - "ca.org1.example.com: 192.168.1.101"
      - "ca.org2.example.com: 192.168.1.102"
      - "zookeeper0: 192.168.1.103"
      - "zookeeper1: 192.168.1.104"
      - "zookeeper2: 192.168.1.105"
      - "kafka0: 192.168.1.106"
      - "kafka1: 192.168.1.107"
      - "kafka2: 192.168.1.108"
      - "kafka3: 192.168.1.109"
      - "orderer0.example.com: 192.168.1.110"
      - "orderer1.example.com: 192.168.1.111"
      - "orderer2.example.com: 192.168.1.112"
      - "peer0.org1.example.com: 192.168.1.113"
      - "peer1.org1.example.com: 192.168.1.114"
      - "peer0.org2.example.com: 192.168.1.115"
      - "peer1.org2.example.com: 192.168.1.116"

